"use strict";

// Generated by CoffeeScript 2.3.2
(function () {
  var preProcessMd, through;
  through = require("through"); // Process markdown before it is rendered.

  module.exports = preProcessMd = function preProcessMd() {
    return through(function (data) {
      var pageBreak;
      pageBreak = '\n\n <div style="page-break-after:always"></div> \n\n';
      return this.queue(data + pageBreak);
    });
  };
}).call(void 0);
//# sourceMappingURL=preProcessMd.js.map
