"use strict";

// Generated by CoffeeScript 2.3.2
(function () {
  var config, extension, fs, getFilePaths, markdownpdf, path;
  markdownpdf = require("markdown-pdf");
  fs = require("fs");
  path = require("path");
  config = require('./config'); // Check if a given file with the given filepath matches a markdown file.

  extension = function extension(element) {
    var extName;
    extName = path.extname(element);
    return extName === ".md";
  }; // Get all .md files from the given path.


  getFilePaths = function getFilePaths() {
    return fs.readdirSync(config.markdownFilesDir).filter(extension).map(function (f) {
      return path.join(config.markdownFilesDir, f);
    });
  }; // Generate PDF file.


  markdownpdf(config.generatorOptions).concat.from(getFilePaths()).to(config.outputPath, function () {
    return console.log("Created output file", config.outputPath);
  });
}).call(void 0);
//# sourceMappingURL=index.js.map
